[2022-10-06T00:38:33.933+0000] {processor.py:156} INFO - Started process (PID=41) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:38:33.934+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:38:33.934+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:38:33.934+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:38:33.936+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:38:33.935+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:38:33.937+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:38:33.953+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.023 seconds
[2022-10-06T00:39:04.262+0000] {processor.py:156} INFO - Started process (PID=105) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:39:04.262+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:39:04.263+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:39:04.263+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:39:04.264+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:39:04.264+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:39:04.264+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:39:04.276+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-06T00:39:34.892+0000] {processor.py:156} INFO - Started process (PID=170) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:39:34.893+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:39:34.893+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:39:34.893+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:39:34.894+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:39:34.894+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:39:34.895+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:39:34.909+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-06T00:40:05.498+0000] {processor.py:156} INFO - Started process (PID=225) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:40:05.499+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:40:05.499+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:40:05.499+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:40:05.500+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:40:05.500+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:40:05.501+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:40:05.511+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-06T00:40:35.535+0000] {processor.py:156} INFO - Started process (PID=289) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:40:35.536+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:40:35.536+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:40:35.536+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:40:35.537+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:40:35.537+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:40:35.537+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:40:35.549+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-06T00:41:06.537+0000] {processor.py:156} INFO - Started process (PID=353) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:41:06.538+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:41:06.538+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:41:06.538+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:41:06.540+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:41:06.539+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:41:06.540+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:41:06.550+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-06T00:41:36.639+0000] {processor.py:156} INFO - Started process (PID=417) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:41:36.639+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:41:36.640+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:41:36.640+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:41:36.642+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:41:36.641+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:41:36.642+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:41:36.654+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-06T00:42:06.664+0000] {processor.py:156} INFO - Started process (PID=472) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:42:06.664+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:42:06.665+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:42:06.665+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:42:06.666+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:42:06.665+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:42:06.666+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:42:06.677+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-06T00:42:37.037+0000] {processor.py:156} INFO - Started process (PID=536) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:42:37.038+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:42:37.038+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:42:37.038+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:42:37.039+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:42:37.039+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:42:37.040+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:42:37.051+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-06T00:43:08.002+0000] {processor.py:156} INFO - Started process (PID=600) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:43:08.003+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:43:08.003+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:43:08.003+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:43:08.005+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:43:08.004+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:43:08.005+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:43:08.015+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-06T00:43:38.024+0000] {processor.py:156} INFO - Started process (PID=664) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:43:38.024+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:43:38.025+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:43:38.025+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:43:38.026+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:43:38.025+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:43:38.026+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:43:38.060+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.038 seconds
[2022-10-06T00:44:08.980+0000] {processor.py:156} INFO - Started process (PID=719) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:44:09.018+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:44:09.018+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:44:09.018+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:44:09.020+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:44:09.019+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:44:09.020+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:44:09.034+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.056 seconds
[2022-10-06T00:44:39.928+0000] {processor.py:156} INFO - Started process (PID=783) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:44:39.928+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:44:39.929+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:44:39.929+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:44:39.930+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:44:39.929+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:44:39.930+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:44:39.941+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.014 seconds
[2022-10-06T00:45:10.674+0000] {processor.py:156} INFO - Started process (PID=847) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:45:10.675+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:45:10.675+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:45:10.675+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:45:10.677+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:45:10.676+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:45:10.677+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:45:10.688+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-06T00:45:41.692+0000] {processor.py:156} INFO - Started process (PID=911) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:45:41.692+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:45:41.692+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:45:41.692+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:45:41.693+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:45:41.693+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:45:41.694+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:45:41.704+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.014 seconds
[2022-10-06T00:46:12.557+0000] {processor.py:156} INFO - Started process (PID=975) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:46:12.567+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:46:12.567+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:46:12.567+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:46:12.569+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:46:12.568+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:46:12.569+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:46:12.580+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.025 seconds
[2022-10-06T00:46:43.329+0000] {processor.py:156} INFO - Started process (PID=1030) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:46:43.329+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:46:43.330+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:46:43.330+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:46:43.331+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:46:43.330+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:46:43.331+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:46:43.342+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-06T00:47:14.231+0000] {processor.py:156} INFO - Started process (PID=1094) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:14.268+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:47:14.269+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:47:14.269+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:14.270+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:47:14.270+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:47:14.270+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:14.282+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.053 seconds
[2022-10-06T00:47:45.287+0000] {processor.py:156} INFO - Started process (PID=1157) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:45.324+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:47:45.325+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:47:45.325+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:45.326+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:47:45.326+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 44
    success =
             ^
SyntaxError: invalid syntax
[2022-10-06T00:47:45.327+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:45.337+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.052 seconds
[2022-10-06T00:47:55.478+0000] {processor.py:156} INFO - Started process (PID=1203) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:55.478+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:47:55.478+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:47:55.478+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:55.546+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:47:55.545+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T00:47:55.546+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:47:55.557+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.081 seconds
[2022-10-06T00:48:25.736+0000] {processor.py:156} INFO - Started process (PID=1268) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:48:25.736+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:48:25.737+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:48:25.737+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:48:25.775+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:48:25.774+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T00:48:25.775+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:48:25.786+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.052 seconds
[2022-10-06T00:48:55.957+0000] {processor.py:156} INFO - Started process (PID=1323) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:48:55.994+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:48:55.994+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:48:55.994+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:48:56.033+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:48:56.032+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T00:48:56.033+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:48:56.043+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.089 seconds
[2022-10-06T00:49:26.883+0000] {processor.py:156} INFO - Started process (PID=1388) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:49:26.884+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T00:49:26.884+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:49:26.884+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:49:26.922+0000] {logging_mixin.py:117} INFO - [2022-10-06T00:49:26.921+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T00:49:26.922+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T00:49:26.933+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.051 seconds
[2022-10-06T23:51:07.130+0000] {processor.py:156} INFO - Started process (PID=42) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:51:07.132+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:51:07.133+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:51:07.132+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:51:07.319+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:51:07.318+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T23:51:07.319+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:51:07.330+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.202 seconds
[2022-10-06T23:51:38.016+0000] {processor.py:156} INFO - Started process (PID=106) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:51:38.017+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:51:38.017+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:51:38.017+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:51:38.061+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:51:38.060+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T23:51:38.062+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:51:38.077+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.062 seconds
[2022-10-06T23:52:08.098+0000] {processor.py:156} INFO - Started process (PID=171) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:52:08.099+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:52:08.099+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:52:08.099+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:52:08.138+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:52:08.138+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T23:52:08.139+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:52:08.150+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.054 seconds
[2022-10-06T23:52:38.360+0000] {processor.py:156} INFO - Started process (PID=233) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:52:38.361+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:52:38.361+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:52:38.361+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:52:38.401+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:52:38.400+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T23:52:38.401+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:52:38.412+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.053 seconds
[2022-10-06T23:53:08.486+0000] {processor.py:156} INFO - Started process (PID=290) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:08.518+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:08.519+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:08.518+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:08.568+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:08.567+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 8, in <module>
    foo = Variable.get("foo")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable foo does not exist'
[2022-10-06T23:53:08.568+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:08.574+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.090 seconds
[2022-10-06T23:53:11.291+0000] {processor.py:156} INFO - Started process (PID=326) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:11.291+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:11.291+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:11.291+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:11.332+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:11.331+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12, in <module>
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
[2022-10-06T23:53:11.332+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:11.344+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.055 seconds
[2022-10-06T23:53:17.716+0000] {processor.py:156} INFO - Started process (PID=337) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:17.716+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:17.717+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:17.717+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:17.764+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:17.763+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    foo = Variable.get("foo")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable foo does not exist'
[2022-10-06T23:53:17.764+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:17.770+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.056 seconds
[2022-10-06T23:53:20.733+0000] {processor.py:156} INFO - Started process (PID=338) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:20.733+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:20.734+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:20.734+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:20.780+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:20.779+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("foo")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable foo does not exist'
[2022-10-06T23:53:20.780+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:20.786+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.055 seconds
[2022-10-06T23:53:22.798+0000] {processor.py:156} INFO - Started process (PID=348) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:22.798+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:22.799+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:22.799+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:22.852+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:22.851+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:53:22.852+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:22.859+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.063 seconds
[2022-10-06T23:53:23.808+0000] {processor.py:156} INFO - Started process (PID=349) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:23.808+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:23.809+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:23.809+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:23.865+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:23.864+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:53:23.865+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:23.872+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.065 seconds
[2022-10-06T23:53:26.889+0000] {processor.py:156} INFO - Started process (PID=350) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:26.889+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:26.889+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:26.889+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:26.945+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:26.944+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:53:26.945+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:26.953+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.066 seconds
[2022-10-06T23:53:27.898+0000] {processor.py:156} INFO - Started process (PID=351) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:27.898+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:27.898+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:27.898+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:27.948+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:27.948+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:53:27.949+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:27.955+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.059 seconds
[2022-10-06T23:53:33.922+0000] {processor.py:156} INFO - Started process (PID=361) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:33.922+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:33.923+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:33.923+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:33.973+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:33.973+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:53:33.973+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:33.980+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.060 seconds
[2022-10-06T23:53:40.861+0000] {processor.py:156} INFO - Started process (PID=377) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:40.862+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:40.862+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:40.862+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:40.910+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:40.909+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:53:40.910+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:40.917+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.057 seconds
[2022-10-06T23:53:47.039+0000] {processor.py:156} INFO - Started process (PID=408) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:47.045+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:53:47.046+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:47.046+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:47.097+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:53:47.096+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:53:47.097+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:53:47.104+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.066 seconds
[2022-10-06T23:54:17.328+0000] {processor.py:156} INFO - Started process (PID=465) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:54:17.329+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:54:17.329+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:54:17.329+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:54:17.389+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:54:17.388+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:54:17.389+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:54:17.396+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.069 seconds
[2022-10-06T23:54:47.610+0000] {processor.py:156} INFO - Started process (PID=528) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:54:47.648+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:54:47.648+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:54:47.648+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:54:47.693+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:54:47.693+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:54:47.694+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:54:47.700+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.091 seconds
[2022-10-06T23:55:17.755+0000] {processor.py:156} INFO - Started process (PID=592) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:55:17.755+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:55:17.756+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:55:17.756+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:55:17.804+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:55:17.803+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:55:17.804+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:55:17.810+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.058 seconds
[2022-10-06T23:55:48.715+0000] {processor.py:156} INFO - Started process (PID=656) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:55:48.716+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:55:48.716+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:55:48.716+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:55:48.764+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:55:48.763+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11, in <module>
    AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable AWS_ACCESS_KEY_ID does not exist'
[2022-10-06T23:55:48.764+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:55:48.771+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.058 seconds
[2022-10-06T23:56:19.652+0000] {processor.py:156} INFO - Started process (PID=720) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:56:19.690+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:56:19.690+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:56:19.690+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:56:19.737+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:56:19.737+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12, in <module>
    AWS_SECRET_ACCESS_KEY = Variable.get["AWS_SECRET_ACCESS_KEY"]
TypeError: 'method' object is not subscriptable
[2022-10-06T23:56:19.738+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:56:19.744+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.094 seconds
[2022-10-06T23:56:50.721+0000] {processor.py:156} INFO - Started process (PID=775) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:56:50.722+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:56:50.723+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:56:50.722+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:56:50.768+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:56:50.767+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12, in <module>
    AWS_SECRET_ACCESS_KEY = Variable.get["AWS_SECRET_ACCESS_KEY"]
TypeError: 'method' object is not subscriptable
[2022-10-06T23:56:50.768+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:56:50.774+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.055 seconds
[2022-10-06T23:57:20.906+0000] {processor.py:156} INFO - Started process (PID=839) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:20.907+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:57:20.908+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:20.907+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:20.954+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:20.954+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12, in <module>
    AWS_SECRET_ACCESS_KEY = Variable.get["AWS_SECRET_ACCESS_KEY"]
TypeError: 'method' object is not subscriptable
[2022-10-06T23:57:20.954+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:20.961+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.056 seconds
[2022-10-06T23:57:25.941+0000] {processor.py:156} INFO - Started process (PID=849) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:25.942+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:57:25.942+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:25.942+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:25.943+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:25.943+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    AWS_SECRET_ACCESS_KEY = Variable.get("AWS_SECRET_ACCESS_KEY"]
                                                                ^
SyntaxError: invalid syntax
[2022-10-06T23:57:25.944+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:25.955+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-06T23:57:27.952+0000] {processor.py:156} INFO - Started process (PID=850) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:27.952+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:57:27.953+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:27.953+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:28.004+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:28.004+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 109, in <module>
    write_twitter_df > raw_to_trusted
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 973, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): raw_to_trusted>) is not an outlet
[2022-10-06T23:57:28.004+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:28.010+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.060 seconds
[2022-10-06T23:57:45.123+0000] {processor.py:156} INFO - Started process (PID=864) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:45.123+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:57:45.124+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:45.124+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:45.179+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:57:45.178+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 109, in <module>
    write_twitter_df > raw_to_trusted
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 973, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): raw_to_trusted>) is not an outlet
[2022-10-06T23:57:45.179+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:57:45.186+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.065 seconds
[2022-10-06T23:58:16.184+0000] {processor.py:156} INFO - Started process (PID=928) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:58:16.184+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:58:16.185+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:58:16.184+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:58:16.240+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:58:16.239+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 109, in <module>
    write_twitter_df > raw_to_trusted
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 973, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): raw_to_trusted>) is not an outlet
[2022-10-06T23:58:16.240+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:58:16.247+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.065 seconds
[2022-10-06T23:58:46.344+0000] {processor.py:156} INFO - Started process (PID=992) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:58:46.345+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:58:46.346+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:58:46.346+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:58:46.398+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:58:46.398+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 109, in <module>
    write_twitter_df > raw_to_trusted
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 973, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): raw_to_trusted>) is not an outlet
[2022-10-06T23:58:46.398+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:58:46.406+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.064 seconds
[2022-10-06T23:59:16.514+0000] {processor.py:156} INFO - Started process (PID=1054) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:59:16.515+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:59:16.515+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:59:16.515+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:59:16.577+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:59:16.577+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 109, in <module>
    write_twitter_df > raw_to_trusted
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 973, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): raw_to_trusted>) is not an outlet
[2022-10-06T23:59:16.578+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:59:16.586+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.074 seconds
[2022-10-06T23:59:46.699+0000] {processor.py:156} INFO - Started process (PID=1109) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:59:46.700+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-06T23:59:46.700+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:59:46.700+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:59:46.752+0000] {logging_mixin.py:117} INFO - [2022-10-06T23:59:46.752+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 109, in <module>
    write_twitter_df > raw_to_trusted
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 973, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): raw_to_trusted>) is not an outlet
[2022-10-06T23:59:46.752+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-06T23:59:46.758+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.061 seconds
